### PR TITLE
Revert "Use Binder build API and remove trigger_binder.py and selenium dependency"

### PR DESCRIPTION
**Pull request by jpivarski**
Reverts scikit-hep/uproot#202

### CODE REVIEW

**Comment by jpivarski** [comment]
@matthewfeickert: This is a PR to reverse the changes. I'm going to make you an uproot contributor so that you can edit this one directly.

**Comment by matthewfeickert** [comment]
@jpivarski Thanks. I'm following up with the Binder team about this one at the moment. It is strange that it is getting caught up like it is.

**Comment by jpivarski** [comment]
I'm going to merge this PR so that I have a working version to test things against. You can open a new PR when you hear back from the Binder team.

Also, I think we can test these by doing an explicit "Trigger build" in Travis; that's what I'll do next time before merging into master.

And above all, thanks!

**Comment by matthewfeickert** [comment]
> I'm going to merge this PR so that I have a working version to test things against.

@jpivarski Sure sounds good. Sorry this didn't go off without a hitch. I'll ping you with a new PR once things are sorted.

> Also, I think we can test these by doing an explicit "Trigger build" in Travis; that's what I'll do next time before merging into master.

Yeah, I usually just create a branch that I'll delete later from the PR branch and then modify the CI on it to trigger the whole CI to make sure it works the way I was thinking. Since I didn't have permissions to start a CI build on a non-PR branch before I didn't attempt that here before requesting your review.

**Comment by jpivarski** [comment]
> Since I didn't have permissions to start a CI build on a non-PR branch before I didn't attempt that here before requesting your review.

I mean, that's something I'd have to do. I did a merge earlier because I didn't know of this option, but now I do and that's how I'll do it.

**Pull request merged**
