### PR TITLE
Use Binder build API and remove trigger_binder.py and selenium dependency

### PR DESCRIPTION
**Pull request by matthewfeickert**
This PR is the effectively the same as [`pyhf` PR 383](https://github.com/diana-hep/pyhf/pull/383).

To summarize it here as well:

```
* Use the Binder build API endpoint with Python's built in webbrowser to trigger builds
   - https://gitter.im/jupyterhub/binder?at=5c2f87038dafa715c73ff54f
   - https://github.com/jupyterhub/binderhub/blob/9ca8fa68bb8b69c6a2736f2275279583073f314f/examples/binder-api.py#L28
* Remove selenium and chromium-chromedriver dependency installation from Travis CI docs stage
* Remove binder/trigger_binder.py as being able to access the API makes it unnecessary
```

This effectively reverts parts of PR #149 and PR #153

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@jpivarski This is ready for review now. Please let me know if you have any questions. Also, happy New Year. :slightly_smiling_face:

**Comment by jpivarski** [comment]
I don't think it's working. It's getting stuck in the

```bash
python -m webbrowser "https://mybinder.org/build/gh/scikit-hep/uproot/master"
```

line (which produces a lot of unreadable characters, reproduced below from the raw log; [see also here](https://travis-ci.org/scikit-hep/uproot/jobs/476338562)).

```
[0Ktravis_fold:start:before_install.3
[0Ktravis_time:start:30ef29e6
[0K$ pip install --upgrade pip setuptools wheel
Collecting pip
  Using cached https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/37/06/754589caf971b0d2d48f151c2586f62902d93dc908e2fd9b9b9f6aa3c9dd/setuptools-40.6.3-py2.py3-none-any.whl
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/ff/47/1dfa4795e24fd6f93d5d58602dd716c3f101cfd5a77cd9acbe519b44a0a9/wheel-0.32.3-py2.py3-none-any.whl
Installing collected packages: pip, setuptools, wheel
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
  Found existing installation: setuptools 38.2.4
    Uninstalling setuptools-38.2.4:
      Successfully uninstalled setuptools-38.2.4
  Found existing installation: wheel 0.30.0
    Uninstalling wheel-0.30.0:
      Successfully uninstalled wheel-0.30.0
Successfully installed pip-18.1 setuptools-40.6.3 wheel-0.32.3
travis_time:end:30ef29e6:start=1546867307959800577,finish=1546867310789348756,duration=2829548179
[0Ktravis_fold:end:before_install.3
[0Ktravis_fold:start:install
[0Ktravis_time:start:1336ccd7
[0K$ pip install -U -q .
travis_time:end:1336ccd7:start=1546867310793768284,finish=1546867313141201255,duration=2347432971
[0Ktravis_fold:end:install
[0Ktravis_time:start:24dc03fb
[0K$ python -m webbrowser "https://mybinder.org/build/gh/scikit-hep/uproot/master"
[?1049h[H[2J[40;1HOpening[Csocket...[1;1H[40;1Hmybinder.[Crg contacted.[CWaiting[Cfor[Creply...[1;1H[40;16H[K[40;1HHTTP/1.1 200[COK[1;1H[1;1Hdata:[C{"phase":[C"built",[C"imageName":[C"gcr.io/binder-prod/r2d-72d7634-scikit-2dh[3;1Hdata:[C{"phase":[C"launching",[C"message":[C"Launching[Cserver...\n"}[5;1H:keepalive[7;1Hdata:[C{"phase":[C"ready",[C"message":[C"server[Crunning[Cat[Chttps://hub.mybinder.org/[40;1H[K[7mâ‰ª â†‘ â†“ Viewing[SSL] <master>[0m[1;1H[?1001s[?1000h[?1000l[?1001r[?1001s[?1000h[?1006h
```

**Comment by jpivarski** [comment]
It eventually ends with

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by matthewfeickert** [comment]
@jpivarski This is strange as you can see from the [Travis CI logs here](https://travis-ci.org/diana-hep/pyhf/jobs/476208099#L919-L934) that we didn't have the same problem when doing the exact same thing on `pyhf`.

This 

```
$ python -m webbrowser "https://mybinder.org/build/gh/scikit-hep/uproot/master"
ybinder.ageName":essage":essage":ybinder.org/≪ ↑ ↓ Viewing[SSL] <master>
```

is really quite strange in my mind, so I'm going to follow up with the Binder team on their Gitter.

**Pull request merged**
