### PR TITLE
Fix reading with HTTP and improve tests

### LINKED ISSUE #422: Test suite with two failing tests
On the current master (6e89ce655) I have two failing tests in `tests/test_tree.py`, see below.

Should the first one check for a raised `NonImplementedError`, maybe?

```
░ tgal@staticbox:uproot  remotes/upstream/master uproot 
░ 13:52:48 128 > pip freeze           
attrs==19.3.0
awkward==0.12.18
cachetools==4.0.0
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
idna==2.8
importlib-metadata==1.3.0
lz4==2.2.1
mock==3.0.5
more-itertools==8.0.2
numpy==1.17.4
packaging==19.2
pandas==0.25.3
pluggy==0.13.1
py==1.8.0
pycparser==2.19
pyparsing==2.4.5
pytest==5.3.2
python-dateutil==2.8.1
pytz==2019.3
requests==2.22.0
six==1.13.0
-e git+git@github.com:tamasgal/uproot.git@6e89ce6556fe204ee4cc9e0c0c06f6d78f97503b#egg=uproot
uproot-methods==0.7.2
urllib3==1.25.7
wcwidth==0.1.7
xxhash==1.4.3
zipp==0.6.0
zstandard==0.12.0
░ tgal@staticbox:uproot  remotes/upstream/master uproot 
░ 13:53:33 > python --version   
Python 3.7.4
```

Test suite run:

```
tests/test_tree.py .F.......F..........................                                                                    [ 87%]
```

Failures:

```python
============================================================ FAILURES ============================================================
______________________________________________ Test.test_branch_auto_interpretation ______________________________________________

self = <tests.test_tree.Test testMethod=test_branch_auto_interpretation>

    def test_branch_auto_interpretation(self):
        # The aim is to reduce this list in a controlled manner
        known_branches_without_interp = [
            b'event',
            b'TObject',
            b'fClosestDistance',
            b'fEvtHdr',
            b'fTracks',
            b'fTracks.fPointValue',
            b'fTriggerBits',
            b'fTriggerBits.TObject'
        ]
        path = os.path.join("tests", "samples", "Event.root")
        if os.path.exists(path):
            tree = uproot.open(path)["T"]
        else:
            tree = uproot.open("http://scikit-hep.org/uproot/examples/Event.root")["T"]
        branches_without_interp = [b.name for b in tree.allvalues() if b.interpretation is None]
        assert branches_without_interp == known_branches_without_interp
        assert tree.array("fTracks.fTArray[3]", entrystop=10)[5][10].tolist()  == [11.03951644897461, 19.40645980834961, 34.54059982299805]
        assert tree.array("fTracks.fCharge", entrystop=10)[0][0:10].tolist()   == [1.0, 1.0, 1.0, 1.0,-1.0, 0.0, 1.0, 0.0, 0.0, 0.0]
>       assert tree.array("fMatrix[4][4]", entrystop=10)[0][1].tolist()        == [-0.13630907237529755, 0.8007842898368835, 1.706235647201538, 0.0]

tests/test_tree.py:634: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
uproot/tree.py:500: in array
    return tbranch.array(interpretation=interpretation, entrystart=entrystart, entrystop=entrystop, flatten=flatten, awkwardlib=awkwardlib, cache=cache, basketcache=basketcache, keycache=keycache, executor=executor, blocking=blocking)
uproot/tree.py:1381: in array
    basket_itemoffset = self._basket_itemoffset(interpretation, basketstart, basketstop, keycache)
uproot/tree.py:1334: in _basket_itemoffset
    for j, key in enumerate(self._threadsafe_iterate_keys(keycache, True, basketstart, basketstop)):
uproot/tree.py:1040: in _threadsafe_iterate_keys
    key = self._basketkey(keysource, i, complete)
uproot/tree.py:1757: in _basketkey
    return self._BasketKey(source.parent(), Cursor(self._fBasketSeek[i]), self.compression, complete)
uproot/tree.py:1635: in __init__
    self._fNbytes, self._fVersion, self._fObjlen, self._fDatime, self._fKeylen, self._fCycle, self._fSeekKey, self._fSeekPdir = cursor.fields(source, TBranchMethods._BasketKey._format_small)
uproot/source/cursor.py:46: in fields
    return format.unpack(source.data(start, stop))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <uproot.source.http.HTTPSource object at 0x7f350fac69d0>, start = 8166160, stop = 8166186, dtype = None

    def data(self, start, stop, dtype=None):
        if dtype is None:
            thedtype = numpy.dtype(numpy.uint8)
        else:
            thedtype = dtype
    
        # assert start >= 0
        # assert stop >= 0
        # assert stop >= start
    
        chunkstart = start // self._chunkbytes
        if stop % self._chunkbytes == 0:
            chunkstop = stop // self._chunkbytes
        else:
            chunkstop = stop // self._chunkbytes + 1
    
        out = numpy.empty((stop - start) // thedtype.itemsize, dtype=thedtype)
    
        for chunkindex in range(chunkstart, chunkstop):
            chunk = None
            if self._futures is not None:
                future = self._futures.pop(chunkindex, None)
                if future is not None:
                    chunk = future.result()
    
            if chunk is None:
                try:
                    chunk = self.cache[chunkindex]
                except KeyError:
                    self._open()
                    chunk = self._read(chunkindex)
    
            cstart = 0
            cstop = self._chunkbytes
            gstart = chunkindex * self._chunkbytes
            gstop = (chunkindex + 1) * self._chunkbytes
    
            if len(chunk) > self._chunkbytes:
                if not numpy.array_equal(chunk[:4], list(b"root")):
>                   raise NotImplementedError("Expected {0} or fewer bytes but received {1} and data does not appear to be an entire ROOT file.".format(self._chunkbytes, len(chunk)))
E                   NotImplementedError: Expected 1048576 or fewer bytes but received 1048577 and data does not appear to be an entire ROOT file.

uproot/source/chunked.py:125: NotImplementedError
_____________________________________________________ Test.test_hist_in_tree _____________________________________________________

self = <tests.test_tree.Test testMethod=test_hist_in_tree>

    def test_hist_in_tree(self):
        path = os.path.join("tests", "samples", "Event.root")
        if os.path.exists(path):
            tree = uproot.open(path)["T"]
        else:
            tree = uproot.open("http://scikit-hep.org/uproot/examples/Event.root")["T"]
        check = [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
                 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0,
                 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0,
                 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 1.0,
                 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0,
                 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]
    
>       assert tree.array("fH")[20].values.tolist() == check

tests/test_tree.py:611: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
uproot/tree.py:500: in array
    return tbranch.array(interpretation=interpretation, entrystart=entrystart, entrystop=entrystop, flatten=flatten, awkwardlib=awkwardlib, cache=cache, basketcache=basketcache, keycache=keycache, executor=executor, blocking=blocking)
uproot/tree.py:1381: in array
    basket_itemoffset = self._basket_itemoffset(interpretation, basketstart, basketstop, keycache)
uproot/tree.py:1334: in _basket_itemoffset
    for j, key in enumerate(self._threadsafe_iterate_keys(keycache, True, basketstart, basketstop)):
uproot/tree.py:1040: in _threadsafe_iterate_keys
    key = self._basketkey(keysource, i, complete)
uproot/tree.py:1757: in _basketkey
    return self._BasketKey(source.parent(), Cursor(self._fBasketSeek[i]), self.compression, complete)
uproot/tree.py:1635: in __init__
    self._fNbytes, self._fVersion, self._fObjlen, self._fDatime, self._fKeylen, self._fCycle, self._fSeekKey, self._fSeekPdir = cursor.fields(source, TBranchMethods._BasketKey._format_small)
uproot/source/cursor.py:46: in fields
    return format.unpack(source.data(start, stop))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <uproot.source.http.HTTPSource object at 0x7f3510c6f4d0>, start = 1171681, stop = 1171707, dtype = None

    def data(self, start, stop, dtype=None):
        if dtype is None:
            thedtype = numpy.dtype(numpy.uint8)
        else:
            thedtype = dtype
    
        # assert start >= 0
        # assert stop >= 0
        # assert stop >= start
    
        chunkstart = start // self._chunkbytes
        if stop % self._chunkbytes == 0:
            chunkstop = stop // self._chunkbytes
        else:
            chunkstop = stop // self._chunkbytes + 1
    
        out = numpy.empty((stop - start) // thedtype.itemsize, dtype=thedtype)
    
        for chunkindex in range(chunkstart, chunkstop):
            chunk = None
            if self._futures is not None:
                future = self._futures.pop(chunkindex, None)
                if future is not None:
                    chunk = future.result()
    
            if chunk is None:
                try:
                    chunk = self.cache[chunkindex]
                except KeyError:
                    self._open()
                    chunk = self._read(chunkindex)
    
            cstart = 0
            cstop = self._chunkbytes
            gstart = chunkindex * self._chunkbytes
            gstop = (chunkindex + 1) * self._chunkbytes
    
            if len(chunk) > self._chunkbytes:
                if not numpy.array_equal(chunk[:4], list(b"root")):
                    raise NotImplementedError("Expected {0} or fewer bytes but received {1} and data does not appear to be an entire ROOT file.".format(self._chunkbytes, len(chunk)))
                self.cache = {}
                for i in range(0, len(chunk), self._chunkbytes):
                    self.cache[i // self._chunkbytes] = chunk[i:i+self._chunkbytes]
                chunk = self.cache[chunkindex]
                # Dismiss any pending futures as everything has already been loaded
                self.dismiss()
            else:
                self.cache[chunkindex] = chunk
    
            if gstart < start:
                cstart += start - gstart
                gstart += start - gstart
            if gstop > stop:
                cstop -= gstop - stop
                gstop -= gstop - stop
    
            if cstop - cstart > len(chunk):
>               raise IndexError("indexes {0}:{1} are beyond the end of data source {2}".format(gstart + len(chunk), stop, repr(self.path)))
E               IndexError: indexes 1171682:1171707 are beyond the end of data source 'http://scikit-hep.org/uproot/examples/Event.root'

uproot/source/chunked.py:143: IndexError
=========================================== 2 failed, 105 passed, 2 skipped in 10.92s ============================================
```

### PR DESCRIPTION
**Pull request by chrisburr**
Fixes #422 and adjusts the test suite to make skipped tests more obvious.

### CODE REVIEW

**Comment by tamasgal** [comment]
I just checked out your branch and it the tests pass!

**Comment by jpivarski** [comment]
This is looking good. Thanks for making the skipped tests more obvious—I'm fully using pytest now (as opposed to the old unittest), but these tests were legacy and hadn't been switched over to using `pytest.skip` yet.

Is the PR done? Do you want me to merge it when all tests pass? I'm planning to include this in a semi-major uproot release today.

Thank you very much!

**Comment by chrisburr** [comment]
As I was already looking at it I also wanted to completely disable skipping tests in CI to avoid accidental mistakes.

I'm done now assuming the tests pass.

**Comment by chrisburr** [comment]
@jpivarski Tests are passing so over to you!

(I've overwhelmed Appyveyor but it passed for [this build](https://ci.appveyor.com/project/jpivarski/uproot/builds/29630486) and only the travis config has changed since then so it's safe to merge.)

**Comment by jpivarski** [comment]
Okay, thanks. I've been watching this progress.

**Pull request merged**
