### PR TITLE
Deal with fixed size arrays as part of jagged one

### PR DESCRIPTION
**Pull request by plexoos**
This is a proposed fix for reading a branch introduced earlier in the Event.root test

### CODE REVIEW

**Comment by plexoos** [comment]
I agree we should have such test. I was actually thinking about a bit more comprehensive one. What about reading values into a dataframe and compare them directly via df.equals() to a reference? Ideally, we would write a tree with uproot and read it back, then compare. But since the writing functionality is not available we can save the dataframe to a hdf5 file and read it back from there. The hdf5 format preserves all types of the dataframe columns.

**Comment by jpivarski** [comment]
It doesn't have to involve writing—the feature you've added is a reading feature, so it can just be

```python
assert tree.array("branch", entrystop=10).tolist() == [...]
```

where `...` is whatever you get from the first 10 events.

In fact, even if the writing feature existed, it wouldn't be a unit test to check both in the same test—it would be an integration test and we'd still need a unit test to narrow in on an error should one occur.

**Comment by plexoos** [comment]
Feel free to modify as you wish

**Comment by jpivarski** [comment]
Perfect! Do you want me to accept this now or were you planning more for this PR?

**Comment by plexoos** [comment]
I don't have anything to add to this PR. Please merge. Thank you!

**Pull request merged**
