### PR TITLE
Applied changes in issue #217 of original repository scikit-hep/uproot.

### PR DESCRIPTION
**Pull request by HealthyPear**

### CODE REVIEW

**Comment by jpivarski** [comment]
Congrats on your first public pull request! I've made a few edits:

   * don't overshadow the `path` variable (introduced a new name, `thispath`)
   * added `reportfile` (get file objects) to `reportpath` (get path strings) so that the user doesn't have to reopen files (possibly many times during the processing of a single file), but `reportpath` is still available for that convenience
   * generalized `yield` processing, so it's clear where to put more of these in the future, should they be added
   * added help support

The order is also different from how you set it up, so you'll need to adjust your (less than a day old) scripts. These "reports" should either all go before the arrays or all go after the arrays, not a mix, and `reportentries` has already set the convention to _before_.

The tests are running. Let me know at any time if you approve these changes; if you do, I'll merge it in.

**Comment by jpivarski** [comment]
Silence implies consent: if I don't hear from you, I'll just merge this PR.

**Comment by HealthyPear** [comment]
Hello,

actually, silence can mean also that I couldn't answer in time :)
I apologize for the delay, I just had the opportunity to modify the code by adding your edits...

I confirm that the current behavior is compatible with the last commit and that I am also able to see the file object printed when enabling "reportfile".

Thank you,
Best regards

**Comment by jpivarski** [comment]
Sorry— I was a little too glib.  :)  Anyway, it should be posted to PyPI for "pip install" as version 3.3.5 shortly. Thanks for this new feature!

**Pull request merged**
