### PR TITLE
Fix length of streamers

### PR DESCRIPTION
**Pull request by reikdas**
It was working all these days because the streamer key's fNbytes and fObjlen got adjusted accordingly.

### CODE REVIEW

**Comment by reikdas** [comment]
@jpivarski The appeveyor test seems to have failed because of a Connection Error. Do you know how to restart the test?

**Comment by jpivarski** [comment]
Apparently, I have the power to do it when I log into AppVeyor using my GitHub account. Do you? I wonder if it depends on developer vs administrator access to the GitHub repo. But you have to explicitly log into AppVeyor (an be out keeps logging me out after a day or two).

**Comment by chrisburr** [comment]
> Apparently, I have the power to do it when I log into AppVeyor using my GitHub account. Do you? I wonder if it depends on developer vs administrator access to the GitHub repo. But you have to explicitly log into AppVeyor (an be out keeps logging me out after a day or two).

It seems like AppVeyor is running under your account rather than the `scikit-hep` organisation.

**Comment by jpivarski** [comment]
Actually, I need to move all of the uproot, uproot-methods, and awkward repos and packages to SciKit-HEP accounts, now that they exist. PyPI, for instance, needs to have transferred ownership, and I guess AppVeyor does as well. I'll try asking Eduardo about this in person today.

**Comment by reikdas** [comment]
@jpivarski Could you restart the appveyor build? (Also, did you get a chance to look at the PR?)

**Comment by jpivarski** [comment]
I restarted it, but this isn't sustainable. I just tried accessing the URL manually and it worked, but we can't keep it in our tests if it's this finicky. If it comes up again, let's just turn off the tests that require this file (two of them, I think).

I didn't realize there was a non-WIP PR open. Could you go to that PR and ping me with an @ sign so that I can look right to it?

My attention is diffuse; I'm sorry about missing the fact that you've been waiting.

**Comment by reikdas** [comment]
> I didn't realize there was a non-WIP PR open. Could you go to that PR and ping me with an @ sign so that I can look right to it?

This is the non WIP PR. 
The PR that I am still working on is this - https://github.com/scikit-hep/uproot/pull/258

**Comment by jpivarski** [comment]
I'll merge it, too, since it looks like you're ready.

**Comment by eduardo-rodrigues** [comment]
Reminds me: @chrisburr, you still need to send me a way to add me to the Scikit-HEP account … You could SMS me some info or put info in 1-2 random temporary files on lxplus or ...

**Pull request merged**
