### PR TITLE
Have Selenium properly wait for page load

### PR DESCRIPTION
**Pull request by matthewfeickert**
Have Selenium properly wait for the Binder page to load to trigger the Binder build. Just using `time.sleep` is not necessarily sufficient. This is done following the example at [How to get Selenium to wait for page load after a click](http://www.obeythetestinggoat.com/how-to-get-selenium-to-wait-for-page-load-after-a-click.html).

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@jpivarski Sorry, this is a quick followup to PR #149. I recently discovered on pyhf that in some instances just using sleep is not sufficient to trigger the page and so this PR has selenium properly wait using its browser tools.

**Comment by jpivarski** [comment]
Is this PR now complete?

**Comment by matthewfeickert** [comment]
> Is this PR now complete?

Yes, this is done and ready for review.

**Comment by jpivarski** [comment]
This is only changing trigger_binder.py, so I'll trust that it's appropriate. (I guess we'll see on the next unrelated code update— timeout for XRootD.)

**Pull request merged**
