### PR TITLE
Adding test and support for None for flatten

### PR DESCRIPTION
**Pull request by henryiii**
This addresses #156 , it makes `flatten=None` a possible option when filtering; unlike `False`, this simply removes anything that would need flattening, rather than making them lists. It also adds an *expected failing* test for the current broken `flatten=True` behavior.

### CODE REVIEW

**Comment by henryiii** [comment]
Tests are passing now. Added pandas testing, but not on PyPy. (The `=True` bug is still present, I think you can fix that more easily than I).

**Comment by jpivarski** [comment]
I plan to check this, correct the None case, and migrate to pytest tomorrow.

**Comment by henryiii** [comment]
Since the default case is `True` and is currently broken, you might want to think about setting "False" as the default when you fix it - since no one can be using the default at the moment. That would be more consistent with the rest of uproot, and is a less surprising default, I think. Just a thought.

**Comment by jpivarski** [comment]
I'll fix it before merging this PR. The only exceptions I want the user to see are ones that say how their inputs were wrong (or external things, like filesystem access, etc.).

As for consistency, I actively decided that `flatten` would be `False` for all array-fetching methods except `TTree.pandas.df`. This one is different because it's a connector to an external library, and the usual thing you'll want to do in that library is to flatten the columns, putting the structure into the index.

Actually, there are two ways to fill a DataFrame. You can use the normal array-fetching methods (`TTree.arrays`, etc.) with `outputtype=pandas.DataFrame` or the connector method. In the former, you get the normal defaults because you're just saying that you want a different output type; in the later, you're primarily thinking about Pandas and what's normal in that world. That's the reason for the different defaults.

In fact, the connector method is just a repackaging of the normal method with different defaults. That's all it does. (As you've seen.) Is that a terrible idea? Should consistency win over my guess at user expectations? (Although it's probably too late to change now— it's been public API for a while.)

**Comment by henryiii** [comment]
However, given that the public API is currently broken, it gives us some leeway to change it. I don't think I'd recommend getting rid of it, since it's more discoverable than `.array(outputtype=pandas.DataFrame)`, but having matching defaults might be better if this is the only one that's different. What defaults are different, besides the flatten?

Also, flatten=True in my case (300+ regular columns and a small handful of jagged columns) would probably waste much more memory than flatten=False, and I don't think most users expect multi-index DataFrames.

**Comment by jpivarski** [comment]
I'm closing this here to continue on #160 (this PR + my changes).

**Comment by henryiii** [comment]
You can always push to my branch, by default you have access to when someone makes a PR. But that's fine. :)

**Comment by jpivarski** [comment]
Darn; I wanted to do that but the text output from my git command suggested this way, so I thought I couldn't push to it. I'll do more Googling and get it right next time.

**Pull request closed without merging**
