### PR TITLE
Fix issue340

### LINKED ISSUE #340: Error reading with uproot root files, with TTree, written with uproot
Hi I tried the example in the README to write TTree in root file but when I try to read it back I get the following error.

```
In [1]: import uproot

In [2]: import numpy as np

In [3]: with uproot.recreate("example.root") as f:
   ...:     f["t"] = uproot.newtree({"normal": np.float64})
   ...:     f["t"].extend({"normal": np.random.normal(0, 1, 10000)})
   ...:

In [4]: t = uproot.open("example.root")["t"]

In [5]: t
Out[5]: <TTree b't' at 0x00010e1e50f0>

In [6]: t.arrays()
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-6-6502dc56ca9a> in <module>
----> 1 t.arrays()

/usr/local/lib/python3.7/site-packages/uproot/tree.py in arrays(self, branches, outputtype, namedecode, entrystart, entrystop, flatten, flatname, awkwardlib, cache, basketcache, keycache, executor, blocking)
    513
    514         # start the job of filling the arrays
--> 515         futures = [(branch.name if namedecode is None else branch.name.decode(namedecode), interpretation, branch.array(interpretation=interpretation, entrystart=entrystart, entrystop=entrystop, flatten=(flatten and not ispandas), awkwardlib=awkward, cache=cache, basketcache=basketcache, keycache=keycache, executor=executor, blocking=False)) for branch, interpretation in branches]
    516
    517         # make functions that wait for the filling job to be done and return the right outputtype

/usr/local/lib/python3.7/site-packages/uproot/tree.py in <listcomp>(.0)
    513
    514         # start the job of filling the arrays
--> 515         futures = [(branch.name if namedecode is None else branch.name.decode(namedecode), interpretation, branch.array(interpretation=interpretation, entrystart=entrystart, entrystop=entrystop, flatten=(flatten and not ispandas), awkwardlib=awkward, cache=cache, basketcache=basketcache, keycache=keycache, executor=executor, blocking=False)) for branch, interpretation in branches]
    516
    517         # make functions that wait for the filling job to be done and return the right outputtype

/usr/local/lib/python3.7/site-packages/uproot/tree.py in array(self, interpretation, entrystart, entrystop, flatten, awkwardlib, cache, basketcache, keycache, executor, blocking)
   1360             keycache = {}
   1361
-> 1362         basket_itemoffset = self._basket_itemoffset(interpretation, basketstart, basketstop, keycache)
   1363         basket_entryoffset = self._basket_entryoffset(basketstart, basketstop)
   1364

/usr/local/lib/python3.7/site-packages/uproot/tree.py in _basket_itemoffset(self, interpretation, basketstart, basketstop, keycache)
   1315         for j, key in enumerate(self._threadsafe_iterate_keys(keycache, True, basketstart, basketstop)):
   1316             i = basketstart + j
-> 1317             numitems = interpretation.numitems(key.border, self.basket_numentries(i))
   1318             basket_itemoffset.append(basket_itemoffset[-1] + numitems)
   1319         return basket_itemoffset

/usr/local/lib/python3.7/site-packages/uproot/interp/numerical.py in numitems(self, numbytes, numentries)
    150         dtype, shape = _dtypeshape(self.fromdtype)
    151         quotient, remainder = divmod(numbytes, dtype.itemsize)
--> 152         assert remainder == 0
    153         return quotient
    154

AssertionError:
```

### PR DESCRIPTION
**Pull request by reikdas**
Fixes #340 
My understanding of the fLast attribute of the TKey of TBaskets was wrong.
Added some more tests.

### CODE REVIEW

**Comment by jpivarski** [comment]
Let me know when you think this is done and want it to be merged. Thanks!

**Comment by reikdas** [comment]
It is done and can be merged :)

**Comment by jpivarski** [comment]
Great! I'll do that (once the tests pass) and you can tell Matthieu that it's fixed, if you haven't already. (Has the version number been bumped? If so, I'll make a new release as well.)

**Comment by reikdas** [comment]
> and you can tell Matthieu that it's fixed, if you haven't already.

I'll comment on the issue once this PR has been merged.

> (Has the version number been bumped? If so, I'll make a new release as well.)

Yes :) 
(Note - I made another PR today where I did not bump the version number, so if that get merged there could be just one release with both the changes?)

**Comment by jpivarski** [comment]
I didn't realize there was another PR. Maybe it would be easier if you merge both, draft a release, and then point me to the draft?

**Comment by reikdas** [comment]
I have drafted a release (https://github.com/scikit-hep/uproot/releases) but perhaps we should wait till I add the fix for append? It is trivial and I should get it done very soon.

**Comment by jpivarski** [comment]
Sure, I'll wait. Just let me know when.

**Pull request merged**
