### PR TITLE
Implement #444

### PR DESCRIPTION
**Pull request by ast0815**
I have implemented the changes discussed in #444. The tests currently fail, because this branch is based on @kreczko's branch for fixing #447. It uses the same sample root file for the tests. I did not touch the test for #447, which is why that still fails.

### CODE REVIEW

**Comment by jpivarski** [comment]
@kreczko, does any of this duplicate or conflict with your PR? Can we merge the efforts?

**Comment by ast0815** [comment]
I just rebased my changes to start on the correct commit from @kreczko's pull request.

**Comment by kreczko** [comment]
hmm..it is not easy to see. There are definitely related elements, but the use case is different.

`_provenance` from MR #459 can definitely be used to construct the `iteritems` and is probably doable for sub-branches.

We used to do something similar but would simply generate additional aliases for sub-branch access on top of uproot (wrapping uproot and directly mapping to provided numpy arrays):

```python

# class providing recursive mapping
class MyAliasTree(dict):
  ...

t = MyAliasTree(filename)
t['l1CaloTowerEmuTree/L1CaloTowerTree/CaloTP/nECALTP'] == t['l1CaloTowerEmuTree/L1CaloTowerTree']['CaloTP/nECALTP'] ==
t['l1CaloTowerEmuTree/L1CaloTowerTree']['CaloTP']['nECALTP']
```

**Comment by ast0815** [comment]
I'm not sure additional aliases would solve this. If you have multiple levels of nested trees, then each (sub-)^n branch can have n different aliases depending on what tree level you are asking. Also the aliases for subbranches on different subtrees might be identical as seen from their respective subtree, so when questioning the base tree you get chances for confusion again. Or maybe I am misunderstanding the suggestion.

**Comment by ast0815** [comment]
Is there a planned way forward with this? Anything I could do?

**Comment by jpivarski** [comment]
This has been in limbo for a while—I just noticed it when scanning through old issues.

This feature, as I understand it, exists in Uproot4 (much easier to write it anew than change the assumptions of an existing codebase). If what you see there is what you were wanting, then there may be nothing to do. If you try it out (in Uproot4) and find that it's not quite right, let me know how it could be better.

In either case, let me know if you want to keep this PR open or to retire it.

**Comment by ast0815** [comment]
I'll have another look at some point and probably rebase this now that #453 is merged.

**Comment by jpivarski** [comment]
Considering that Uproot 4 will be replacing Uproot 3 this year, the higher priority would be to be sure that the feature exists in Uproot 4. Since you're more familiar with what this is supposed to do, could you determine whether Uproot 4's implementation satisfies the requirement? (It was about slashes in key strings, right? I made sure to include that in the new version, but is it done right, as you would want it?)

**Comment by ast0815** [comment]
I'll give it a look. 👍

**Comment by ast0815** [comment]
Hello again,

I just checked and it seems like addressing subbranches from file and tree level with '/' as level separator works as intended in uproot4. I could not find any `up.iterate` or `up.pandas.iterate` function though, so I could not test whether it supports the use case that originally prompted me to find the issue. I.e. I wanted to iterate over many root files and get pandas DataFrames with columns from nested branches when the explicit branch name was not unique.

**Comment by jpivarski** [comment]
I've been focusing on deserializing all the data types, but since I'll want to present it soon, I was planning on adding `iterate` next. (Maybe tomorrow, after porting all the old `test_issues.py`.) So you're right that `uproot.iterate` isn't there yet.

As part of a general campaign of unifying things, `uproot.pandas.iterate` is going to be `library="pd"` on `uproot.iterate`. The `library` parameter determines the output library; `library="np"` means NumPy (even if jagged: we make NumPy object arrays if need be), `library="ak"` is Awkward, `library="pd"` is Pandas (Series and DataFrames), and `library="cp"` is CuPy (GPUs). Others may be added in the future.

**Comment by ast0815** [comment]
Anything else I should do for this to be merged?

**Comment by jpivarski** [comment]
That works! Thanks!

**Pull request merged**
