### PR TITLE
More histogram intro

### PR DESCRIPTION
**Pull request by HDembinski**
Minimal extension of the README, which shows how to get the most important data of a histogram. Perhaps some link to uproot-methods should be added as well, to point to further information.

### CODE REVIEW

**Comment by jpivarski** [comment]
Looks good. Is the `h.variances` in that example supposed to be empty because there's no `_fSumw2`? Should it perhaps be `None` or `numpy.sqrt(h.values)` instead?

**Comment by jpivarski** [comment]
If the `h.variances` interface changes, the README will have to change, but I'm leaving that for the future.

**Comment by jpivarski** [comment]
Ah wait— I needed to read that in context. I'll edit on master (it's a README).

**Comment by jpivarski** [comment]
I misspoke: `variances` would be equal to `values` without a `_fSumw2`, not the square root. (I'm thinking "errors.") I think we're in agreement, then.

**Comment by HDembinski** [comment]
Yes. :)

**Pull request merged**
