### PR TITLE
Add support for Python 3.9

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
Final PR after similar PRs in `uproot-methods` and `awkward-array` for the `uproot 3` suite to support Python 3.9, which is relevant as a LTS version.

### CODE REVIEW

**Review by jpivarski — APPROVED** [review]
The changes look good. Just waiting for the rest results...

**Comment by eduardo-rodrigues** [comment]
Random time-outs in Travis are responsible for the 1-2 failures. In other terms, this is actually ready to be merged IMO.

Looking forward to the subsequent release of the `uproot 3` suite for Python 3.9 :-).

**Comment by eduardo-rodrigues** [comment]
@chrisburr, it may be better to revert to conda. There are issues with what you replaced with and, as said, things are in fact all OK in reality.

**Comment by chrisburr** [comment]
@eduardo-rodrigues They're not random failures. All of the failures were for the Python 2.7 job and retrying didn't help.

So far as I know all of the old mamba issues have been fixed so I'm interested in reporting anything that remains upstream. I'll give up and revert if it starts to become time consuming to fix.

**Comment by eduardo-rodrigues** [comment]
Understood, thanks.

**Comment by chrisburr** [comment]
@jpivarski It looks like my changes worked but I can revert them if you'd prefer?

FYI: Travis CI is shutting down .org at the end of the year and there is no longer a free tier on .com (I guess it doesn't really matter given uproot4 is mostly ready to take over).

**Comment by chrisburr** [comment]
Apparently you merged as I was writing that, I'll assume you're happy 😄

**Comment by eduardo-rodrigues** [comment]
Thanks for the info @chrisburr. Most org packages now use Azure pipelines or GitHub actions, hence not a problem.

**Comment by jpivarski** [comment]
@chrisburr Sorry, our actions crossed!

The awkward0/uproot3 branches will be replaced with awkward1/uproot4 by December 1 (https://indico.cern.ch/event/960587/contributions/4070318/), so it's okay if it hobbles along.

I had no idea that Travis will be shutting down. It has been a lot of trouble—Azure Pipelines and GitHub Actions have been a lot easier to deal with. But I guess the timing is perfect: I wouldn't want to port these tests.

Thanks again for your help!

**Comment by jpivarski** [comment]
Deployment with Travis took 11 hours! (No errors, just slow. Each task was 1‒5 minutes; it just took a long time to get any time on them. I guess that's why they're giving up the free service, especially with so many competitors.)

**Pull request merged**
