### PR TITLE
Read RNTuple anchor

### PR DESCRIPTION
**Pull request by jpivarski**

### CODE REVIEW

**Comment by jpivarski** [comment]
Commit 317c6c44e5348145ad288d93068efc19d2c79cf7 was unintentionally added, but it's not a problem. We wanted to bump the version number anyway.

**Comment by jpivarski** [comment]
@oshadura This PR passes tests, but I can keep it open in case you run into anything else that needs to be fixed at the uproot level, anything that could help you figure out how to deserialize RNTuple in Python. If, on the other hand, you think this is all that's necessary, I can merge it so that you can work from a released version.

**Comment by oshadura** [comment]
Hi Jim! I realized that the easiest way is to make a rntuple reader as a dependency of uproot, but I can't proceed without your PR :) (particularly without rntuple defined in `builtin_classes`).

**Comment by jpivarski** [comment]
I can't believe I forgot to merge this. I'll also deploy a version soon.

**Comment by oshadura** [comment]
Wonderfu, now I can go ahead full speed!

**Pull request merged**
