### PR TITLE
Enable getitem for TTree to recognize cycle number

### LINKED ISSUE #424: Creating new trees with cycles in the name breaks write-ability
The basic usage works fine

```python
import uproot
import numpy

with uproot.recreate("example.root") as f:
    f["t"] = uproot.newtree({"branch": "int32"})
    f["t"].extend({"branch": numpy.array([1, 2, 3, 4, 5])})
```

however, once you get to using a cycle like so

```
import uproot
import numpy

with uproot.recreate("example.root") as f:
    f["t;1"] = uproot.newtree({"branch": "int32"})
    f["t;1"].extend({"branch": numpy.array([1, 2, 3, 4, 5])})
```

this crashes as `f["t;1"]` stops becoming a `uproot.write.objects.TTree.TTree` and becomes a `uproot.rootio.TTree` instead. This means, among other things, we lose the `extend()` functionality.

### PR DESCRIPTION
**Pull request by reikdas**
Fixes #424

### CODE REVIEW

**Comment by jpivarski** [comment]
Did @kratsg confirm that this branch works in his case? (Although your test does look very similar to his case...)

If so, and if you don't have any other plans for this branch, I'll merge it as soon as the tests pass.

**Comment by reikdas** [comment]
> Did @kratsg confirm that this branch works in his case? (Although your test does look very similar to his case...)

No, waiting to hear back from him. I opened the PR to let you know that I am done (unless he finds some error).

> If so, and if you don't have any other plans for this branch, I'll merge it as soon as the tests pass.

Actually, I might have just noticed some redundency.. could you hold off on the merge for a bit? I'll post here when I am done :)

**Comment by jpivarski** [comment]
Sure. I'll hold off until

   * you say you're done,
   * @kratsg confirms the fix, _and_
   * all tests pass.

Then I'll merge it.

**Comment by reikdas** [comment]
Okay, I am done.

**Comment by kratsg** [comment]
Works for me.

**Comment by jpivarski** [comment]
Great! Merged!

**Pull request merged**
