### PR TITLE
Adding support for IPython key completions

### PR DESCRIPTION
**Pull request by henryiii**
Addressing #151 .

Note that completion looks significantly more useful if you press tab before you type a quote - then the key completions are at the top because it sorts the completions, and the quote `'` causes the key completions to be at the top. Not sure why Jupyter assumes any other sort of completion inside a string for a key...

Only tested locally on Python 3, will use CI to test Python 2.

### CODE REVIEW

**Comment by henryiii** [comment]
PS: I didn't add this method for the custom OrderedDict, since it is left over from Python 2.6 support. I wasn't sure if the file `uproot/write/TFile.py` should have a redirect method for this like the others, depends on if it is user-facing. For now, I've added it.

**Comment by jpivarski** [comment]
Thanks! I had starred your issue to deal with on Monday— it sounds like a great idea. It could apply to TTrees and TBranches as much as TDirectories (and write TFiles). The `;N` is only ever needed if the key name without it is not unique— it doesn't actually have anything to do with directory vs other kind of object.

To see this, consider writing two histograms to a file with the same name. You'd expect the second to overwrite the first, but both get written with different cycle numbers. That's rather unpythonic, but it's a bridge to how ROOT works. Only if cycle numbers are included in the key, it's one key is one object.

**Comment by henryiii** [comment]
I've removed the filtering on TDirectory, just in case there is a `;2` or more. A smart filter could be added, but for completion, I think it's fine to compete with the `;1`, it's both correct and easy to erase.

The current patch does apply to the other cases as well, anything that has a `def keys`, in fact. Select "ignore whitespace for now" on the github diff settings; apparently uproot is a bit messy on ending whitespace. Having your editor filter ending whitespace is not a bad idea, IMHO. ;) I can remove the whitespace changes if you want.

**Comment by jpivarski** [comment]
Oh, you're right: there it is in uproot/tree.py. I don't mind the whitespace changes at all— I remove them when I discover them manually (through a nervous twitch where I control-E at the ends of lines). I suppose it should be something for the editor to do automatically, though.

The test failures were Travis's fault— I reloaded them and they're fine.

**Comment by jpivarski** [comment]
Could you change the version number in uproot/version.py to 3.2.1 so that when I merge this it will be ready to be a new release?

**Comment by henryiii** [comment]
Sure. Is the there a changelog somewhere, or just the GitHub releases?

**Comment by henryiii** [comment]
Bumped version, and removed all EOL whitespace.

On macOS, that's:
```bash
git ls-files '*.h' | xargs sed -i '' 's/[[:space:]]*$//'
```

per file type. (on Linux, you'd drop the `''` after `-i`).

**Comment by jpivarski** [comment]
Thanks! I know of a way to edit through the website for non-pull requests, now I just need to learn to do that for pull requests (because we always need a version bump). I don't like doing that on master because it triggers more CI machinery (and using "[skip ci]" would then add that message to the last commit before the release, causing the release to not do CI, which is bad because that's how we deploy!).

Changing every single file in the repository is a bit terrifying, but I see nothing wrong with this particular change. The tests were successful, so now I'll merge. Once that goes through, I'll deploy a new version to PyPI and we'll see a complete test of #149.

**Comment by jpivarski** [comment]
> Sure. Is the there a changelog somewhere, or just the GitHub releases?

There's just the GitHub releases, which taken together has the contents of what I would put in a CHANGELOG. Do you have a reason why a single file is preferable?

If so, I could start that discipline by gathering release messages and then keeping them in sync from here on out.

**Comment by henryiii** [comment]
For a CHANGELOG in the source, it's nice, but releases work too. As long as there's a log somewhere...

**Comment by jpivarski** [comment]
The full chain seems to have worked! This is now in PyPI. I'll start on an AUTHORS file on Monday morning.

**Pull request merged**
