### PR TITLE
Fixes issue #327.

### PR DESCRIPTION
**Pull request by jpivarski**
The regular expression that derives streamer names from TBranch-defining comments was too naive: the type name is in parentheses, but the _last_ set of parentheses. ALICE uses parentheses in its comments for other purposes.

Fixed the bug, added a test, and bumped the version number.

### CODE REVIEW

**Comment by HimanshuCERN** [comment]
Hi Jim,
As you committed the changes, I upgrded to uproot 3.9.2, but I am still facing the same problem when I try to load the tree.

f.get("DstTree");

Output ----

KeyError                                  Traceback (most recent call last)
<ipython-input-7-aed60a3a3196> in <module>
----> 1 f.get("DstTree")

~/alice/sw/ubuntu1804_x86-64/Python-modules/1.0-1/lib/python/site-packages/uproot/rootio.py in get(self, name, cycle)
    354 
    355             if last is not None:
--> 356                 return last.get()
    357             elif cycle is None:
    358                 raise _KeyError("not found: {0}\n in file: {1}".format(repr(name), self._context.sourcepath))

~/alice/sw/ubuntu1804_x86-64/Python-modules/1.0-1/lib/python/site-packages/uproot/rootio.py in get(self, dismiss)
    914 
    915         try:
--> 916             return _classof(self._context, self._fClassName).read(self._source, self._cursor.copied(), self._context, self)
    917         finally:
    918             if dismiss:

~/alice/sw/ubuntu1804_x86-64/Python-modules/1.0-1/lib/python/site-packages/uproot/rootio.py in read(cls, source, cursor, context, parent)
    857         out = cls.__new__(cls)
    858         out = cls._readinto(out, source, cursor, context, parent)
--> 859         out._postprocess(source, cursor, context, parent)
    860         return out
    861 

~/alice/sw/ubuntu1804_x86-64/Python-modules/1.0-1/lib/python/site-packages/uproot/tree.py in _postprocess(self, source, cursor, context, parent)
    290 
    291         for branch in self._fBranches:
--> 292             self._attachstreamer(branch, context.streamerinfosmap.get(getattr(branch, "_fClassName", None), None), context.streamerinfosmap, False)
    293 
    294         self._branchlookup = {}

~/alice/sw/ubuntu1804_x86-64/Python-modules/1.0-1/lib/python/site-packages/uproot/tree.py in _attachstreamer(self, branch, streamer, streamerinfosmap, isTClonesArray)
    282                     pass
    283 
--> 284                 self._attachstreamer(subbranch, submembers.get(name, None), streamerinfosmap, isTClonesArray)
    285 
    286     def _postprocess(self, source, cursor, context, parent):

~/alice/sw/ubuntu1804_x86-64/Python-modules/1.0-1/lib/python/site-packages/uproot/tree.py in _attachstreamer(self, branch, streamer, streamerinfosmap, isTClonesArray)
    249                 if typename == b'TClonesArray' and m is not None:
    250                     typename = m.group(1)
--> 251                 members = streamerinfosmap[typename].members
    252         elif isinstance(streamer, uproot.rootio.TStreamerSTL):
    253             try:

KeyError: b'NEW) (AliReducedFMDInfo'

**Comment by jpivarski** [comment]
I think you're not getting the changes. Check your version number. (Maybe pip pulled from its cache, or maybe you requested it before it had fully deployed. It seems to be on PyPI now.)

**Comment by HimanshuCERN** [comment]
Yes! I think I should clean the environment first. There were two versions of uproot... 

Thanks!!

**Comment by HimanshuCERN** [comment]
Hi JIm
I got the changes. Now it is working well.

Thanks!

**Pull request merged**
